### ISSUE TITLE
[Discussion] Make it a file with a list of hirings

### ISSUE THREAD

**Issue by Dun-sin** [ykdojo/open-source-hiring#1]
I thought about this, we could build a website that gets the data from the `jobs.json` file that people will contribute to when a new job is available 

OR

Have the jobs in `readme.md` making it easy for people to add jobs

OR

Make it in category for jobs to make it easy for people to search and add 
E.g 3 files front-end-jobs.json, back-end-jobs.json, devops-jobs.json

What do you think?

**Comment by ykdojo** [comment]
Starting with README might be good.

Then, once people like the idea, we can move on to one of the json formats.

Either way, love the idea!

**Comment by Dun-sin** [comment]
Can I work on the readme file?

**Comment by Shukla007** [comment]
Yes, Starting with a readme file is a good idea 💜 .

Once people start liking the idea then we can move on.

I also want to work on this project.

**Comment by ykdojo** [comment]
Yes of course! Feel free to send a PR as you see fit
